# -*- coding: utf-8 -*-
"""Balance volumétrico.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qtkRSfWNv8tdB2hgpqzx7f8NnR7ebqnN

# Balance Volumetrico
## FWKO
"""

import pandas as pd
import math

#Primero pedimos al usuario que ingrese los datos
BFPD=float(input("Ingrese el caudal del fluido(BFPD): "))
API=float(input("Ingrese los grados API del petróleo: "))
BSW=float(input("Ingrese el BSW del fluido(porcentaje): "))
#Creo que es FWKO porque wash tank trabaja con bsw < 1% y ppm < 100 xd
efi=float(input("Ingrese la eficiencia del FWKO: "))
ppm=float(input("Ingrese las partes por millon del FWKO: "))
#Acá le pido las ppm del wash tank
ppmw=float(input("Ingrese las partes por millon del wash tank: "))

#Hacemos los calculos
#Puse las funciones que saqué para no pedirle el % de agua emulsionada
if(API<=20 and API>0):
 porc=math.ceil((-5/3)*API+55)
 print("Su % de agua emulsionada es: ",porc) 
elif (API>20 and API<45):
  porc=math.ceil((-5/8)*API+133/4);
  print("Su % de agua emulsionada es: ",porc)
BWPD = (BSW/100)*BFPD;
BOPD = BFPD-BWPD;
emul = BOPD*100/(100-porc);
aemul = emul*(porc/100);
alib = BWPD-aemul;

# Crear un DataFrame vacío con 6 filas y 8 columnas
tabla = pd.DataFrame(index=range(7), columns=range(8))
# Agregar datos a la tabla
#Completamos la tabla Datos
tabla.iloc[0,0] = "Datos"
tabla.iloc[1,0] = "Oil"
tabla.iloc[2,0] = "Water"
tabla.iloc[3,0] = "Emulsión"
tabla.iloc[4,0] = "A.Libre"
tabla.iloc[5,0] = "A.Residual"
tabla.iloc[6,0] = "Total"
#Les damos valor a cada uno
tabla.iloc[1,1] = BOPD
tabla.iloc[2,1] = BWPD
tabla.iloc[3,1] = emul
tabla.iloc[4,1] = alib
tabla.iloc[5,1] = "-"
tabla.iloc[6,1] = "-"
#Iteración 1 (A)
#Calculos
nwalib=alib*(100-efi)/100
#Relleno de tabla
T1A=nwalib+emul
#Iteración 1 (B)
tabla.iloc[1,2] = BOPD
tabla.iloc[2,2] = aemul
tabla.iloc[3,2] = emul
tabla.iloc[4,2] = nwalib
tabla.iloc[5,2] = "-"
tabla.iloc[6,2] = T1A
#Iteración 1 (B)
#Calculos
alib2=alib-nwalib
T1B=alib2
#Relleno de tabla
tabla.iloc[1,5] = "-"
tabla.iloc[2,5] = alib2
tabla.iloc[3,5] = "-"
tabla.iloc[4,5] = alib2
tabla.iloc[5,5] = "-"
tabla.iloc[6,5] = T1B
#Iteración 2 (A)
#Calculos
are=(alib2*ppm)/(1*10**6-ppm)
nwoil=BOPD-are
nwwater=(nwoil*porc)/(100-porc)
nwemul=(nwoil*100)/(100-porc)
T2A=nwalib+nwemul
#Relleno de tabla
tabla.iloc[1,3] = nwoil
tabla.iloc[2,3] = nwwater
tabla.iloc[3,3] = nwemul
tabla.iloc[4,3] = nwalib
tabla.iloc[5,3] = "-"
tabla.iloc[6,3] = T2A
#Iteración 2 (B)
#Calculos
ww=aemul-nwwater
nwalib2=alib2+ww
T2B=nwalib2+are
#Relleno de tabla
tabla.iloc[1,6] = are
tabla.iloc[2,6] = ww
tabla.iloc[3,6] = "-"
tabla.iloc[4,6] = nwalib2
tabla.iloc[5,6] = are
tabla.iloc[6,6] = T2B
#Iteración 3 (A)
#Calculos
nware=(nwalib2*ppm)/(1*10**6-ppm)
nwoil1=nwoil-(nware-are)
nwwater1=(nwoil1*porc)/(100-porc)
nwemul1=(nwoil1*100)/(100-porc)
T3A=nwalib+nwemul1
#Relleno de tabla
tabla.iloc[1,4] = nwoil1
tabla.iloc[2,4] = nwwater1
tabla.iloc[3,4] = nwemul1
tabla.iloc[4,4] = nwalib
tabla.iloc[5,4] = "-"
tabla.iloc[6,4] = T3A
#Iteración 3 (B)
#Calculos
nwalib3=nwalib2+(nwwater-nwwater1)
T3B=nwalib3+nware
#Relleno de tabla
tabla.iloc[1,7] = nware
tabla.iloc[2,7] = nwwater-nwwater1
tabla.iloc[3,7] = "-"
tabla.iloc[4,7] = nwalib3
tabla.iloc[5,7] = nware
tabla.iloc[6,7] = T3B

tabla.iloc[0,1] = "Inlet"
tabla.iloc[0,2] = "Interación 1 (A)"
tabla.iloc[0,3] = "Interación 2 (A)"
tabla.iloc[0,4] = "Interación 3 (A)"
tabla.iloc[0,5] = "Interación 1 (B)"
tabla.iloc[0,6] = "Interación 2 (B)"
tabla.iloc[0,7] = "Interación 3 (B)"
print(tabla)

from pandas.core.groupby.groupby import T
#A continuacion hacemos el balance volumetrico
TOTAL=T1A+T1B
TOTAL2=T2A+T2B
TOTAL3=T3A+T3B
#Completar tablas 
tabla1 = pd.DataFrame(index=range(3), columns=range(4))
tabla1.iloc[0,0] = "Total A"
tabla1.iloc[1,0] = "Total B"
tabla1.iloc[2,0] = "Total"

tabla1.iloc[0,1] = T1A
tabla1.iloc[1,1] = T1B
tabla1.iloc[2,1] = TOTAL

tabla1.iloc[0,2] = T2A
tabla1.iloc[1,2] = T2B
tabla1.iloc[2,2] = TOTAL2

tabla1.iloc[0,3] = T3A
tabla1.iloc[1,3] = T3B
tabla1.iloc[2,3] = TOTAL3
print(tabla1)

"""## Wash Tank


"""

# Crear un DataFrame vacío con 6 filas y 8 columnas
entwash=nwalib+nwemul1
print("Sus datos de entrada en el wash tank son: ",entwash) 
tabla2 = pd.DataFrame(index=range(6), columns=range(4))
# Agregar datos a la tabla
#Completamos la tabla Datos
tabla2.iloc[0,0] = "Datos" 
tabla2.iloc[1,0] = "Oil"
tabla2.iloc[2,0] = "Emulsión"
tabla2.iloc[3,0] = "A.Libre"
tabla2.iloc[4,0] = "A.Emulsionada"
tabla2.iloc[5,0] = "Total"

#Calculos
ww2=nwwater1+nwalib             #Agua
mm2=(nwoil1*((0.5)/99.5))       #Agua emulsionada
alw2=ww2-mm2
arw2=(alw2*ppmw)/(1000000-ppmw)
nwoil2=nwoil1-arw2
aei2=(nwoil2*((0.5)/99.5))
alw3=ww2-aei2
arw3=(alw3*ppmw)/(1000000-ppmw)
nwoil3=nwoil1-arw2
aei3=(nwoil3*((0.5)/99.5))
alw4=ww2-aei3

#Iteracion 1
Tw1a=nwoil1+mm2
tabla2.iloc[1,1] = nwoil1
tabla2.iloc[2,1] = nwoil1+mm2
tabla2.iloc[3,1] = "-"
tabla2.iloc[4,1] = mm2
tabla2.iloc[5,1] = Tw1a

tabla2.iloc[0,1] = "Interación 1 (A)"
tabla2.iloc[0,2] = "Interación 2 (A)"
tabla2.iloc[0,3] = "Interación 3 (A)"

#Iteracion 2
Tw2a=nwoil2+aei2
tabla2.iloc[1,2] = nwoil2
tabla2.iloc[2,2] = nwoil2+aei2
tabla2.iloc[3,2] = "-"
tabla2.iloc[4,2] = aei2
tabla2.iloc[5,2] = Tw2a

#Iteracion 3
Tw3a=nwoil3+aei3
tabla2.iloc[1,3] = nwoil3
tabla2.iloc[2,3] = nwoil3+aei3
tabla2.iloc[3,3] = "-"
tabla2.iloc[4,3] = aei3
tabla2.iloc[5,3] = Tw3a

print(tabla2)
# Crear un DataFrame vacío con 6 filas y 8 columnas
tabla3 = pd.DataFrame(index=range(5), columns=range(4))
# Agregar datos a la tabla
#Completamos la tabla Datos
tabla3.iloc[0,0] = "Datos"
tabla3.iloc[1,0] = "A.Libre"
tabla3.iloc[2,0] = "A.Emulsionada"
tabla3.iloc[3,0] = "A.Residual"
tabla3.iloc[4,0] = "Total"

Tw1b=alw2
tabla3.iloc[1,1] = alw2
tabla3.iloc[2,1] = "-"
tabla3.iloc[3,1] = "-"
tabla3.iloc[4,1] = Tw1b

#Encabezados
tabla3.iloc[0,1] = "Interación 1 (B)"
tabla3.iloc[0,2] = "Interación 2 (B)"
tabla3.iloc[0,3] = "Interación 3 (B)"

#Iteracion 2
Tw2b=alw3+arw2
tabla3.iloc[1,2] = alw3
tabla3.iloc[2,2] = "-"
tabla3.iloc[3,2] = arw2
tabla3.iloc[4,2] = Tw2b

#Iteracion 3
Tw3b=alw4+arw3
tabla3.iloc[1,3] = alw4
tabla3.iloc[2,3] = "-"
tabla3.iloc[3,3] = arw3
tabla3.iloc[4,3] = Tw3b

print(tabla3)

from pandas.core.groupby.groupby import T
#A continuacion hacemos el balance volumetrico
TOTAL4=Tw1a+Tw1b
TOTAL5=Tw2a+Tw2b
TOTAL6=Tw3a+Tw3b
#Completar tablas 
tabla2 = pd.DataFrame(index=range(3), columns=range(4))
tabla2.iloc[0,0] = "Total A"
tabla2.iloc[1,0] = "Total B"
tabla2.iloc[2,0] = "Total"

tabla2.iloc[0,1] = Tw1a
tabla2.iloc[1,1] = Tw1b
tabla2.iloc[2,1] = TOTAL4

tabla2.iloc[0,2] = Tw2a
tabla2.iloc[1,2] = Tw2b
tabla2.iloc[2,2] = TOTAL5

tabla2.iloc[0,3] = Tw3a
tabla2.iloc[1,3] = Tw3b
tabla2.iloc[2,3] = TOTAL6
print(tabla2)